sources:
  - build/LXGWWenKaiLite-Light.ufo
  - build/LXGWWenKaiLite-Regular.ufo
  - build/LXGWWenKaiLite-Medium.ufo
  - build/LXGWWenKaiMonoLite-Light.ufo
  - build/LXGWWenKaiMonoLite-Regular.ufo
  - build/LXGWWenKaiMonoLite-Medium.ufo
reverseOutlineDirection: False
removeOutlineOverlaps: False
buildOTF: False
buildTTF: True
buildWebfont: False
autohintTTF: False
autohintOTF: False

outputDir: ../fonts
ttDir: $outputDir/TTF
otDir: $outputDir/OTF